### ISSUE TITLE
Local client connection

### ISSUE THREAD

**Issue by JevLOMCN** [damianday/Conquer#20]
Issue: Local Client stuck at gates when the Account Server and Game Server is set up publicly. (Others can connect outside my network)

*Account Server:

- !ServerInfo

[
  {
    "ServerName": "LOMCN",
    "TicketAddressIP": "127.0.0.1",
    "TicketAddressPort": 6678,
    "PublicAddressIP": "Public_IP", (Hidden obvs)
    "PublicAddressPort": 8701
  }
]

- !Settings

{
  "LocalListeningIP": "192.168.1.27", (My PC's IPV4)
  "LocalListeningPort": 7000,
  "TicketSendingPort": 6678
}

*Game Server:

- !Settings

  "UserConnectionIP": "192.168.1.27", (My PC's IPV4)
  "UserConnectionPort": 8701,
  "TicketReceivePort": 6678,

*Local Client

- !Settings

{
  "AccountServerAddressIP": "192.168.1.27", (My PC's IPV4)
  "AccountServerAddressPort": 7000,
  "SaveAccountName": "Gamemaster",
  "SaveArea": "LOMCN"
}

Note: 127.0.0.1 also doesn't work

Not sure why my Local Client wont connect.

**Comment by damianday** [comment]
Does your Launcher connect to the AccountServer? if it does, when you log in with the launcher does it print a message about generating a ticket for your connection.

**Comment by JevLOMCN** [comment]
> Does your Launcher connect to the AccountServer? if it does, when you log in with the launcher does it print a message about generating a ticket for your connection.

Yes it does ask about a ticket

**Comment by JevLOMCN** [comment]
![image](https://github.com/damianday/Conquer/assets/68875342/cb5e013a-fe41-4aa3-a42d-b1d410e2a06e)

**Comment by damianday** [comment]
I can reproduce this, hopefully will have a fix by end of day.

**Comment by damianday** [comment]
The issue is that the firewall needs to allow port 7000 and 8701, that should fix the issue, please reopen if it continues.

**Comment by JevLOMCN** [comment]
![image](https://github.com/damianday/Conquer/assets/68875342/17954809-8e30-4a45-ae28-b0b16bcc88b7)

7000 and 8701 Ported on both Windows Firewall and my Router. Note same ports opened via Outbound windows firewall too

Running Client on 192.168.1.27 (IPV4) still gets me stuck at Gates.
